### ISSUE TITLE
Corrigir a lógica de validação para soma de tempos

### ISSUE THREAD

**Issue by augusto-herrmann** [economiagovbr/api-pgd#11]
A API atualmente [valida a carga horária total](https://github.com/economiagovbr/api-pgd/blob/main/schemas.py#L65), verificando se é igual à soma dos tempos. Entretanto, essa lógica está errada e precisa ser modificada.

**Comment by augusto-herrmann** [comment]
@nitaibezerra , onde podemos encontrar a descrição da regra de negócio correta para a validação da soma de tempos?

**Comment by nitaibezerra** [comment]
A regra correta é que a soma de todos os tempos de execução (`tempo_presencial_executado` e `tempo_teletrabalho_executado`) de todas as atividades deve ser igual a `carga_horaria_total` do Plano de Trabalho. 

Caso alguma atividade não possua um dos dois tempos então a validação não se aplica. Esta condição cobre as situações em que alguma atividade ainda não foi completamente preenchida.

**Comment by augusto-herrmann** [comment]
A `carga_horaria_total` deve ser interpretada como um tempo planejado ou executado?

Caso seja executado, ela não poderia ser preenchida a priori, antes da execução do plano de trabalho.

Caso seja planejado, então a soma a ser considerada é dos tempos da atividade planejados, e não os executados.

Precisamos esclarecer essa dúvida sobre a regra de negócio.

**Comment by augusto-herrmann** [comment]
Após um questionamento feito pelo @nitaibezerra sobre as regras de negócio aqui descritas, pendente de resposta, o desenvolvimento foi despriorizado e pausado na atual sprint.

**Comment by nitaibezerra** [comment]
Após novos esclarecimentos foi decidido por remover e relaxar esse tipo de verificação.
