### ISSUE TITLE
Mensagem de Digitos verificadores do CPF inválidos para CPF Válido

### ISSUE THREAD

**Issue by felipediascade** [economiagovbr/api-pgd#33]
Prezados,

Por gentileza, analisar a regra de validação do CPF. Na nossa base consta um CPF válido que está sendo tratado como inválido.

17:27:08,092 INFO  [stdout] (default task-2) {"detail":[{"loc":["body","cpf"],"msg":"Digitos verificadores do CPF inválidos.","type":"value_error"}]}

**Comment by augusto-herrmann** [comment]
Caro @felipediascade,

a API [já conta com diversos testes](https://github.com/economiagovbr/api-pgd/blob/main/tests/plano_trabalho_test.py#L321) públicos para a validação do CPF e os CPFs de pessoas reais que testamos aqui deram certo. Você poderia passar em privado, por e-mail ou Slack, o número do CPF que está dando problema, para que possamos averiguar o que está ocorrendo?

**Comment by augusto-herrmann** [comment]
Conforme troca de mensagens, o CPF em questão era mesmo inválido e o funcionamento da validação de CPF da API está correto.
